# Host to use for canonical URL generation (without trailing slash)
host: ukhomeoffice-test.github.io/docs-as-code-poc-middleman

# Header-related options
show_govuk_logo: false
service_name: HO Docs-as-code Proof of Concept
service_link: https://ukhomeoffice-test.github.io/docs-as-code-poc-middleman/
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://ukhomeoffice-test.github.io/docs-as-code-poc-middleman/about
  Get Started: https://ukhomeoffice-test.github.io/docs-as-code-poc-middleman/get-started
  Documentation: /
  Support: https://ukhomeoffice-test.github.io/docs-as-code-poc-middleman/support

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: false

# Enable collapsible navigation in the sidebar
collapsible_nav: false

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: UKHomeOffice-test/docs-as-code-poc-middleman
